# Generated by Django 3.1.4 on 2020-12-18 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='create_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='room',
            old_name='quest_can_pause',
            new_name='guest_can_pause',
        ),
    ]
